version: '3.8'

services:
  some-postgres:
    image: postgres:17.0
    container_name: postgres17
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped